ci:
  skip: [jenkinsfilelint]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: debug-statements
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.6
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: local
    # This is a "local" hook to run jenkinsfilelint
    hooks:
      - id: jenkinsfilelint
        name: jenkinsfilelint
        description: Lint Jenkinsfiles and Groovy files.
        entry: jenkinsfilelint
        language: python
        additional_dependencies: ['requests']
        files: (?i)^(.*/)?(Jenkinsfile[^/]*|.*\.groovy)$
        exclude: ^jenkinsfilelint/
        pass_filenames: true
        verbose: true
        stages: [manual]  # pre-commit run jenkinsfilelint --all-files --hook-stage manual
