name: Release Drafter

on:
  push:
    branches:
      - "main"
  # allowing to run manually
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      # Required to create/update the release
      contents: write
      # Required for autolabeler to add labels to PRs
      pull-requests: write
      
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
